### ISSUE TITLE
Enhance description on poggit

### ISSUE THREAD

**Issue by pavog** [nhanaz-pm-pl/OpList#3]
Hi, this plugin shows a list of server operators in the chat when you type in `/oplist`, right?
Why don't you add this to the description on https://poggit.pmmp.io/p/OpList ?
You can also add a screenshot of the output to this page.

Server owners currently can not know what this plugin offers, when they read the description on the poggit website.

**Comment by 0xliam627** [comment]
Sorry, but I have a curious question:
- Why don't you know anything but install it?

**Comment by pavog** [comment]
I did not install it. I read the source code.

**Comment by 0xliam627** [comment]
Lmao

**Comment by NhanAZ** [comment]
You can use `/oplist` or `/ops` to see a list of operators.
I will update the description as soon as possible.
Very sorry for my laziness.

**Comment by NhanAZ** [comment]
Issue solved by https://github.com/nhanaz-pm-pl/OpList/commit/cae48105f193a91c2986751bf828aeb25e5b032c
